### PR TITLE
Create logo.svg

### PR DESCRIPTION
**Pull request by mehanalavimajd**

### CODE REVIEW

**Review by parsampsh — APPROVED** [review]

**Comment by parsampsh** [comment]
Thanks.

**Comment by mehanalavimajd** [comment]
Can you please change by mehanalavimajd to by Mehan

**Comment by parsampsh** [comment]
> Can you please change by mehanalavimajd to by Mehan

Yes sure.

**Comment by parsampsh** [comment]
Done.

**Pull request merged**
